version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./back:/app
      - /app/node_modules
      - ./back/uploads:/app/uploads

volumes:
  uploads: