version: '3.8'

services:
  frontend_python:
    build:
      context: ./front/react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front/react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend_python

  backend_python:
    build:
      context: ./back/python
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back/python:/app
      - ./back/python/uploads:/app/uploads

volumes:
  uploads_python: