version: '3.8'

services:
  frontend:
    build:
      context: ./front/react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front/react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./back/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back/nodejs:/app
      - /app/node_modules
      - ./back/nodejs/uploads:/app/uploads

volumes:
  uploads: